title: Cagatay Guley
description: A Mining Engineer
baseurl: "" 
url: "https://guley.com.tr"
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives